common_packages:
  - ansible
  - bind-utils
  - dos2unix
  - git
  - nano
  - pandoc
  - sqlite
  - stow
  - tig
  - unzip
  - wget
  - zip
  - zsh
  - tcsh
  - policycoreutils
  - alpine-maildir
  - figlet
  - inotify-tools
  - lynx
  - mutt
  - nano
  - nethack
  - nmap-ncat
  - stow
  - tin
  - tmux
  - util-linux-user
  - w3m
  - python3-libsemanage
