---
collections:
    - name: ansible.posix
      version: 1.4.0
    - name: community.general
      version: 5.0.1
    - name: community.crypto
      version: 2.3.0
    - name: community.digitalocean
      version: 1.19.0
