---
collections:
    - name: ansible.posix
      version: 1.4.0
    - name: community.general
      version: 5.5.0
    - name: community.crypto
      version: 2.7.0
    - name: community.digitalocean
      version: 1.21.0
