---
collections:
    - name: ansible.posix
      version: 1.4.0
    - name: community.general
      version: 6.1.0
    - name: community.crypto
      version: 2.9.0
    - name: community.digitalocean
      version: 1.23.0
