---
collections:
    - name: ansible.posix
      version: 1.4.0
    - name: community.general
      version: 5.8.0
    - name: community.crypto
      version: 2.8.1
    - name: community.digitalocean
      version: 1.22.0
