---
collections:
    - name: ansible.posix
      version: 1.4.0
    - name: community.general
      version: 5.1.0
    - name: community.crypto
      version: 2.3.2
    - name: community.digitalocean
      version: 1.20.0
