---
collections:
    - name: ansible.posix
      version: 1.5.1
    - name: community.general
      version: 6.5.0
    - name: community.crypto
      version: 2.11.1
    - name: community.digitalocean
      version: 1.23.0
