---
- name: Install Dovecot
  dnf:
    name: "dovecot"
    state: present
- name: Deploy updated 10-master.conf
  copy:
    src: ../files/dovecot/10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart dovecot

- name: Create dhparam for Dovecot
  command: /usr/bin/openssl dhparam -out /etc/dovecot/dh.pem 4096
  args:
    creates: /etc/dovecot/dh.pem

- name: Check if TLS cert for host exists
  stat:
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
  register: lets_cert
- name: Deploy updated 10-ssl.conf
  template:
    src: ../templates/dovecot/10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: "0644"
  when: lets_cert.stat.exists == true
  notify: restart dovecot

- name: Start dovecot
  service:
    name: dovecot
    state: started
    enabled: yes

- name: Add firewall rule for imaps
  firewalld:
    zone: public
    service: imaps
    permanent: yes
    state: enabled
  when: lets_cert.stat.exists == true
