---
- name: Include certbot role
  ansible.builtin.import_role:
    name: certbot
    allow_duplicates: false

- name: Install Dovecot
  ansible.builtin.package:
    name: "dovecot"
    state: present
- name: Deploy 00-protocols.conf
  ansible.builtin.copy:
    src: dovecot/00-protocols.conf
    dest: /etc/dovecot/conf.d/10-protocols.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart dovecot
- name: Deploy updated 10-master.conf
  ansible.builtin.copy:
    src: dovecot/10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart dovecot

- name: Create dhparam for Dovecot
  ansible.builtin.command: /usr/bin/openssl dhparam -out /etc/dovecot/dh.pem 4096
  args:
    creates: /etc/dovecot/dh.pem

- name: Check if TLS cert for host exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
  register: lets_cert
- name: Deploy updated 10-ssl.conf
  ansible.builtin.template:
    src: dovecot/10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: "0644"
  when: lets_cert.stat.exists
  notify: restart dovecot
- name: Install dovecot restart deploy-hook for certbot
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/dovecot
    mode: "0755"
    owner: root
    group: root
    content: |
      #!/bin/sh
      /bin/systemctl restart dovecot
  when: lets_cert.stat.exists

- name: Check if fail2ban is installed
  ansible.builtin.stat:
    path: "/etc/fail2ban/jail.local"
  register: fail2ban_jail_file
- name: Enable dovecot jail
  community.general.ini_file:
    path: /etc/fail2ban/jail.local
    section: dovecot
    option: enabled
    value: "true"
    mode: "0644"
  when: fail2ban_jail_file.stat.exists
  notify: restart fail2ban

- name: Start dovecot
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true

- name: Add firewall rule for imaps
  ansible.posix.firewalld:
    zone: public
    service: imaps
    permanent: true
    state: enabled
    immediate: true
  when: lets_cert.stat.exists
