---
- name: restart postfix
  service:
    name: postfix
    state: reloaded

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

- name: new virtual aliases
  command: postmap /etc/postfix/virtual

- name: new aliases
  command: newaliases
