---
- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: new virtual aliases  # noqa no-changed-when
  ansible.builtin.command: postmap /etc/postfix/virtual

- name: new aliases  # noqa no-changed-when
  ansible.builtin.command: newaliases
