---
- name: Install disk-usage cronjob
  copy:
    dest: /etc/cron.d/disk-usage
    owner: root
    group: root
    mode: "0600"
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      @daily root bash -c "echo -e \"User disk usage on /home - $(date +%Y-%m-%d)\n\n$(du -xsh /home/*|sort -hr)\" | mail -s \"Disk usage report\" root"
