---
- name: Add Bash config for Maildr
  ansible.builtin.copy:
    src: mail/mail.sh
    dest: /etc/profile.d/mail.sh
    owner: root
    group: root
    mode: "0644"
- name: Add csh config for Maildr
  ansible.builtin.copy:
    src: mail/mail.csh
    dest: /etc/profile.d/mail.csh
    owner: root
    group: root
    mode: "0644"
- name: Copy mutt defaults
  ansible.builtin.copy:
    src: mail/Muttrc.local
    dest: /etc/Muttrc.local
    owner: root
    group: root
    mode: "0644"
