---
- name: Add Bash config for Maildr
  copy:
    src: mail/mail.sh
    dest: /etc/profile.d/mail.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy mutt defaults
  copy:
    src: mail/Muttrc.local
    dest: /etc/Muttrc.local
    owner: root
    group: root
    mode: "0644"
