---
- name: Set Maildir (bash)
  ansible.builtin.copy:
    dest: /etc/profile.d/mail.sh
    owner: root
    group: root
    mode: "0644"
    content: |
      export MAILPATH="$HOME/Maildir/new"

- name: Set Maildir (csh)
  ansible.builtin.copy:
    dest: /etc/profile.d/mail.csh
    owner: root
    group: root
    mode: "0644"
    content: |
      setenv MAILPATH "$HOME/Maildir/new"

- name: Copy mutt defaults
  ansible.builtin.copy:
    src: mail/Muttrc.local
    dest: /etc/Muttrc.local
    owner: root
    group: root
    mode: "0644"
