---
- name: Install Python packages
  ansible.builtin.pip:
    name: "{{ packages }}"
  vars:
    packages:
      - toot

- name: Install group packages
  ansible.builtin.package:
    name: "{{ shell_group_packages }}"
