---
- name: Install Packages
  dnf:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - ansible
      - firewalld
      - mutt
      - zip
      - unzip
      - git
      - tmux
      - nano
      - zsh
      - bind-utils
      - wget
- name: Install Python packages
  pip:
    name: '{{ packages }}'
  vars:
    packages:
      - toot