---
- name: Install Packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ansible
      - bind-utils
      - figlet
      - git
      - lynx
      - mutt
      - nano
      - nmap-ncat
      - tmux
      - unzip
      - wget
      - zip
      - zsh
- name: Install Python packages
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - toot
