---
- name: Install Packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - alpine-maildir
      - ansible
      - bind-utils
      - dos2unix
      - figlet
      - git
      - inotify-tools
      - lynx
      - mutt
      - nano
      - nethack
      - nmap-ncat
      - pandoc
      - sqlite
      - stow
      - tig
      - tmux
      - unzip
      - util-linux-user
      - wget
      - zip
      - zsh
- name: Install Python packages
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - toot
