---
# DCSS
- name: Deploy dcss
  copy:
    src: scripts/dcss
    dest: /usr/local/bin/dcss
    owner: root
    group: root
    mode: "0755"

# MkUser Install
- name: Install mkuser
  ansible.builtin.package:
    name: mkuser
    state: installed
- name: Copy mkuser template
  copy:
    src: mail.tmpl
    dest: /etc/mkuser/mail.tmpl
    owner: root
    group: root
    mode: "0600"
- name: Copy mkuser config
  copy:
    src: mkuser.yaml
    dest: /etc/mkuser/mkuser.yaml
    owner: root
    group: root
    mode: "0600"
