---
# DCSS
- name: Deploy dcss
  copy:
    src: scripts/dcss
    dest: /usr/local/bin/dcss
    owner: root
    group: root
    mode: "0755"

# MkUser Install
- name: Deploy mkuser
  git:
    repo: "https://github.com/dimension-sh/mkuser.git"
    dest: /usr/local/src/mkuser
    version: master
    force: yes
  register: mkuser_repo
- name: Copy mkuser
  copy:
    src: /usr/local/src/mkuser/mkuser
    dest: /usr/local/sbin/mkuser
    owner: root
    group: root
    mode: "0700"
- name: Copy mkuser.1
  copy:
    src: /usr/local/src/mkuser/mkuser.1
    dest: /usr/local/share/man/man1/mkuser.1
    owner: root
    group: root
    mode: "0644"
- name: Create mkuser config directory
  file:
    path: /etc/mkuser
    state: directory
    mode: "0700"
- name: Copy mkuser template
  copy:
    src: mail.tmpl
    dest: /etc/mkuser/mail.tmpl
    owner: root
    group: root
    mode: "0600"
- name: Copy mkuser config
  copy:
    src: mkuser.yaml
    dest: /etc/mkuser/mkuser.yaml
    owner: root
    group: root
    mode: "0600"

# Manuals
- name: Deploy man pages
  git:
    repo: "https://github.com/dimension-sh/man.git"
    dest: /usr/local/src/man
    version: master
  notify: Install man files
