---
# Drivel install
- name: Deploy drivel
  copy:
    src: ../files/scripts/drivel
    dest: /usr/local/bin/drivel
    owner: root
    group: root
    mode: '0755'

# news script install
- name: Deploy news
  copy:
    src: ../files/scripts/news
    dest: /usr/local/bin/news
    owner: root
    group: root
    mode: '0755'
- name: Create the NEWS file
  file:
    path: /usr/local/etc/NEWS
    state: file
    owner: root
    group: root
    mode: '0644'

# DCSS
- name: Deploy dcss
  copy:
    src: ../files/scripts/dcss
    dest: /usr/local/bin/dcss
    owner: root
    group: root
    mode: '0755'

# MkUser Install
- name: Deploy mkuser
  git:
    repo: 'https://github.com/dimension-sh/mkuser.git'
    dest: /usr/local/src/mkuser
    version: master
    force: yes
  register: mkuser_repo
- name: Make mkuser executable
  file:
    path: /usr/local/src/mkuser/mkuser.py
    owner: root
    group: root
    mode: '0700'
  when: mkuser_repo.changed
- name: Link mkuser
  file:
    src: /usr/local/src/mkuser/mkuser.py
    dest: /usr/local/sbin/mkuser
    owner: root
    group: root
    state: link
- name: Create mkuser config directory
  file:
    path: /etc/mkuser
    state: directory
    mode: '0700'
- name: Copy mkuser template
  copy:
    src: /usr/local/src/mkuser/welcome_mail.tmpl
    dest: /etc/mkuser/welcome_mail.tmpl
    force: no

# Manuals
- name: Deploy man pages
  git:
    repo: 'https://github.com/dimension-sh/man.git'
    dest: /usr/local/src/man
    version: master
  register: man_repo
- name: Install man files
  shell:
    cmd: ./install.sh
    chdir: /usr/local/src/man/
  when: man_repo.changed