---
- name: Install talk packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - talk
      - talk-server
      - ytalk
- name: Start ntalk.socket
  ansible.builtin.service:
    name: ntalk.socket
    state: started
    enabled: true
- name: Add firewall rule for ntalk
  ansible.posix.firewalld:
    zone: public
    port: 518/tcp
    permanent: true
    state: enabled
    immediate: true
