---
- name: Install Packages
  dnf:
    name: 'nginx'
    state: present

- name: Add firewall rule for http
  firewalld:
    zone: public
    service: smtp
    permanent: yes
    state: enabled
- name: Add firewall rule for https
  firewalld:
    zone: public
    service: smtp
    permanent: yes
    state: enabled

- name: Deploy website files
  git:
    repo: 'https://github.com/dimension-sh/website.git'
    dest: /var/www/dimension.sh/
    version: master
- name: Create the drivel output file
  file:
    path: /var/www/dimension.sh/inc/drivel.html
    state: file
    owner: root
    group: users
    mode: '0664'

- name: Deploy gen_website_users.py
  copy:
    src: ../files/website/gen_website_users.py
    dest: /etc/cron.hourly/gen_website_users.py
    owner: root
    group: root
    mode: '0755'
- name: Deploy active_users cron
  copy:
    src: ../files/website/active_users
    dest: /etc/cron.d/active_users
    owner: root
    group: root
    mode: '0644'