---
- name: Install Packages
  dnf:
    name: 'nginx'
    state: present
- name: Configure userdirs in nginx
  copy:
    src: ../files/website/userdir.conf
    dest: /etc/nginx/default.d/userdir.conf
    owner: root
    group: root
    mode: '0644'
- name: Configure cgi in nginx
  copy:
    src: ../files/website/cgi.conf
    dest: /etc/nginx/default.d/cgi.conf
    owner: root
    group: root
    mode: '0644'
- name: Reload service nginx, in all cases
  service:
    name: nginx
    state: reloaded

- name: Add firewall rule for http
  firewalld:
    zone: public
    service: smtp
    permanent: yes
    state: enabled
- name: Add firewall rule for https
  firewalld:
    zone: public
    service: smtp
    permanent: yes
    state: enabled

- name: Deploy website files
  git:
    repo: 'https://github.com/dimension-sh/www-site.git'
    dest: /var/www/dimension.sh/
    version: master
- name: Create the drivel output file
  copy:
    content: ""
    dest: /var/www/dimension.sh/inc/drivel.html
    force: no
    owner: root
    group: users
    mode: '0664'
- name: Create cgi directory
  file:
    path: /var/www/cgi
    state: directory
    mode: '0755'
- name: Create requests directory
  file:
    path: /var/www/requests
    state: directory
    mode: '0700'

# CGI scripts
- name: Deploy join.cgi
  copy:
    src: ../files/website/join.cgi
    dest: /var/www/cgi/join.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy users.cgi
  copy:
    src: ../files/website/users.cgi
    dest: /var/www/cgi/users.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy online.cgi
  copy:
    src: ../files/website/online.cgi
    dest: /var/www/cgi/online.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy news.cgi
  copy:
    src: ../files/website/news.cgi
    dest: /var/www/cgi/news.cgi
    owner: root
    group: root
    mode: '0755'
