---
- name: Create DKIM DNS records
  hosts: mail
  become: true
  tasks:
    - name: "Generate DNS record for {{ item }} DKIM key"
      ansible.builtin.shell:
        cmd: "openssl rsa -in /etc/opendkim/keys/{{ ansible_domain }}/{{ item }}.private -pubout -outform der 2>/dev/null | openssl base64 -A"
      register: keys
      loop: "{{ postfix_opendkim_keys }}"
      changed_when: False
      when: postfix_opendkim_enable
    - name: Set DKIM records
      community.digitalocean.digital_ocean_domain_record:
        domain: "{{ ansible_domain }}"
        type: TXT
        name: "{{ item.item }}._domainkey"
        oauth_token: "{{ digitalocean_token }}"
        data: "v=DKIM1; k=rsa; p={{ item.stdout }}"
        ttl: 3600
      loop: "{{ keys.results }}"
      when: postfix_opendkim_enable and item.stdout
