---
- hosts: all
  become: true
  roles:
    - common
    - cis
- hosts: build
  become: true
  roles:
    - gantsign.golang
- hosts: dev
  become: true
  roles:
    - gantsign.golang
- hosts: shell
  become: true
  roles:
    - shell
    - efingerd
    - news
    - www
    - gopher
    - gantsign.golang
    - gemini
- hosts: mail
  become: true
  roles:
    - postfix
    - dovecot
- hosts: services
  become: true
