---
- hosts: all
  become: true
  roles:
    - role: common
    - role: cis
    - role: certbot
    - role: borgmatic
- hosts: build
  become: true
- hosts: dev
  become: true
- hosts: shell
  become: true
  roles:
    - role: shell
    - role: efingerd
    - role: news
    - role: frp
    - role: www
      tags:
        - www
    - role: gopher
      tags:
        - www
    - role: gemini
      tags:
        - www
- hosts: mail
  become: true
  roles:
    - role: postfix
      tags:
        - mail
    - role: dovecot
      tags:
        - mail
- hosts: services
  become: true
