---
- hosts: all
  become: true
  roles:
    - common
    - cis
- hosts: build
  become: true
  roles:
    - build
- hosts: shell
  become: true
  roles:
    - dovecot
    - postfix
    - shell
    - efingerd
    - news
    - www
    - gopher
