[project]
name = "infra"
version = "0.1.0"
description = "Ansible playbook for dimension.sh"
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.9.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.8.1",
]
