---
collections:
  - name: ansible.posix
    version: 1.6.1
  - name: community.general
    version: 10.0.1
  - name: community.crypto
    version: 2.22.3
  - name: community.digitalocean
    version: 1.27.0

roles:
  - name: gantsign.golang
    version: 3.3.6
  - name: nikdoof.borgmatic
    src: https://github.com/nikdoof/ansible-borgmatic
    version: main
  - name: nikdoof.cis
    src: https://github.com/nikdoof/ansible-cis.git
    version: main
  - name: nikdoof.certbot
    src: https://github.com/nikdoof/ansible-certbot.git
    version: main
