---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.2.0
  - name: community.crypto
    version: 2.17.1
  - name: community.digitalocean
    version: 1.26.0

roles:
  - name: gantsign.golang
    version: 3.2.6
  - name: borgmatic
    src: https://github.com/nikdoof/ansible-borgmatic
    version: main
  - name: cis
    src: https://github.com/nikdoof/ansible-cis.git
    version: main
