---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.1.0
  - name: community.crypto
    version: 2.22.3
  - name: community.digitalocean
    version: 1.27.0

roles:
  - name: gantsign.golang
    version: 3.4.0
  - name: nikdoof.borgmatic
    src: https://github.com/nikdoof/ansible-borgmatic
    version: main
  - name: nikdoof.cis
    src: https://github.com/nikdoof/ansible-cis.git
    version: main
  - name: nikdoof.certbot
    src: https://github.com/nikdoof/ansible-certbot.git
    version: main
