---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.1.0
  - name: community.crypto
    version: 2.14.1
  - name: community.digitalocean
    version: 1.23.0

roles:
  - name: gantsign.golang
    version: 3.1.6
  - name: borgmatic
    src: https://github.com/nikdoof/ansible-borgmatic
    version: main
  - name: cis
    src: https://github.com/nikdoof/ansible-cis.git
    version: main
