---
allow_duplicates: false

galaxy_info:
  role_name: borgmatic
  author: Andrew Williams
  description: Installs and configures a Borgmatic
  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: RedHat
      versions:
        - 8
