---
# Config
- name: Create efingerd config directory
  file:
    path: /etc/efingerd
    state: directory
    mode: "0755"
- name: Copy efingerd scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "/etc/efingerd/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - list
    - log
    - luser
    - nouser
    - preamble
- name: Start finger socket
  ansible.builtin.systemd:
    name: finger.socket
    enabled: yes
    state: started
