---
- name: Install efingerd
  dnf:
    name: efingerd
    state: installed
- name: create override folder for finger@.service
  file:
    path: /etc/systemd/system/finger@.service.d
    state: directory
- name: Install systemd overrides
  copy:
    src: override.conf
    dest: /etc/systemd/system/finger@.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
