---
- name: Copy efingerd RPM
  copy:
    src: ../files/bin/efingerd-1.6.5-1.el8.x86_64.rpm
    dest: /usr/local/src/efingerd-1.6.5-1.el8.x86_64.rpm
    owner: root
    group: root
    mode: '0755'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
- name: Install efingerd
  dnf:
    name: /usr/local/src/efingerd-1.6.5-1.el8.x86_64.rpm
    state: installed
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'