---
# news script install
- name: Install lowdown package
  ansible.builtin.package:
    name: lowdown
    state: present
- name: Deploy news
  ansible.builtin.copy:
    src: news
    dest: /usr/local/bin/news
    owner: root
    group: root
    mode: "0755"
- name: Deploy news2md
  ansible.builtin.copy:
    src: news2md
    dest: /usr/local/bin/news2md
    owner: root
    group: root
    mode: "0755"
