---
# news script install
- name: Install pandoc package
  dnf:
    name: pandoc
    state: present
- name: Deploy news
  copy:
    src: news
    dest: /usr/local/bin/news
    owner: root
    group: root
    mode: "0755"
- name: Deploy news2md
  copy:
    src: news2md
    dest: /usr/local/bin/news2md
    owner: root
    group: root
    mode: "0755"
- name: Deploy news.cron
  copy:
    src: news.cron
    dest: /etc/cron.d/news
    owner: root
    group: root
    mode: "0644"
