---
- name: configure virtual aliases
  lineinfile:
    dest: "/etc/postfix/virtual"
    regexp: '^{{ item.virtual | regex_escape }}.*'
    line: '{{ item.virtual }} {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_virtual_aliases }}"
  notify:
    - new virtual aliases
    - restart postfix