---
- name: Set postfix configuration options
  postconf:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  notify: restart postfix
  loop:
    - { name: "inet_interfaces", value: "all" }
    - { name: "myhostname", value: "{{ ansible_fqdn }}" }
    - { name: "mydomain", value: "{{ ansible_domain }}" }
    - { name: "myorigin", value: "$mydomain" }
    - { name: "mydestination", value: "$myhostname, $mydomain"}
    - { name: "mynetworks", value: "{{ postfix_mynetworks | join(' ') }}" }
    - { name: "smtpd_tls_received_header", value: "yes" }
    - { name: "smtp_tls_security_level", value: "may" }
    - { name: "virtual_alias_maps", value: "hash:/etc/postfix/virtual" }
    - { name: "virtual_alias_domains", value: "{{ postfix_virtual_domains | join(' ') }}" }
    - { name: "home_mailbox", value: "Maildir/" }
    - { name: "disable_vrfy_command", value: "yes" }
    - { name: "smtpd_helo_required", value: "yes" }
    - { name: "smtpd_delay_reject", value: "yes" }
    - { name: "smtpd_helo_restrictions", value: "{{ postfix_smtpd_helo_restrictions | join(',') }}" }
    - { name: "smtpd_sender_restrictions", value: "{{ postfix_smtpd_sender_restrictions | join(',') }}" }
    - { name: "smtpd_recipient_restrictions", value: "{{ postfix_smtpd_recipient_restrictions | join(',') }}" }

- name: Check if TLS cert for host exists
  stat:
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
  register: lets_cert
- name: Set postfix TLS configuration options
  postconf:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  notify: restart postfix
  when: lets_cert.stat.exists
  loop:
    - { name: "smtpd_tls_cert_file", value: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem" }
    - { name: "smtpd_tls_key_file", value: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem" }
    - { name: "smtpd_tls_security_level", value: "may" }
    - { name: "smtpd_tls_auth_only", value: "yes" }
- name: Install postfix restart deploy-hook for certbot
  copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/postfix
    mode: "0755"
    owner: root
    group: root
    content: |
      #!/bin/sh
      /bin/systemctl restart postfix
  when: lets_cert.stat.exists

- name: Check if Dovecot is installed
  stat:
    path: "/etc/dovecot/dovecot.conf"
  register: dovecot_conf
- name: Copy submission master.cf
  copy:
    src: master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: "0644"
  when: dovecot_conf.stat.exists
  notify: restart postfix
- name: Copy sender_login_maps.pcre
  copy:
    src: sender_login_maps.pcre
    dest: /etc/postfix/sender_login_maps.pcre
    owner: root
    group: root
    mode: "0644"
  when: dovecot_conf.stat.exists

