---
- name: Set postfix configuration options
  postconf:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  notify: restart postfix
  loop:
    - { name: "inet_interfaces", value: "all" }
    - { name: "myhostname", value: "{{ ansible_fqdn }}" }
    - { name: "mydomain", value: "{{ ansible_domain }}" }
    - { name: "myorigin", value: "$mydomain" }
    - { name: "mydestination", value: "$myhostname, $mydomain"}
    - { name: "mynetworks", value: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128" }
    - { name: "smtpd_tls_received_header", value: "yes" }
    - { name: "smtp_tls_security_level", value: "may" }
    - { name: "virtual_alias_maps", value: "hash:/etc/postfix/virtual" }
    - { name: "virtual_alias_domains", value: "" }
    - { name: "home_mailbox", value: "Maildir/" }
    - { name: "disable_vrfy_command", value: "yes" }
    - { name: "smtpd_helo_required", value: "yes" }
    - { name: "smtpd_delay_reject", value: "yes" }
    - { name: "smtpd_helo_restrictions", value: "permit_mynetworks,reject_non_fqdn_helo_hostname,reject_invalid_helo_hostname,permit" }
    - { name: "smtpd_sender_restrictions", value: "permit_mynetworks,reject_non_fqdn_sender,reject_unknown_sender_domain,permit" }
    - { name: "smtpd_recipient_restrictions", value: "permit_sasl_authenticated,permit_mynetworks,reject_non_fqdn_recipient,reject_unknown_recipient_domain,reject_unauth_destination,permit" }

- name: Check if TLS cert for host exists
  stat: 
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
  register: lets_cert
- name: Set postfix TLS configuration options
  postconf:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  notify: restart postfix
  when: lets_cert.stat.exists == true
  loop:
    - { name: "smtpd_tls_cert_file", value: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem" }
    - { name: "smtpd_tls_key_file", value: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem" }
    - { name: "smtpd_tls_security_level", value: "may" }
    - { name: "smtpd_tls_auth_only", value: "yes" }
    

- name: Check if Dovecot is installed
  stat: 
    path: "/etc/dovecot/dovecot.conf"
  register: dovecot_conf
- name: Set postfix SASL configuration options
  postconf:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  notify: restart postfix
  when: dovecot.stat.exists == true
  loop:
    - { name: "smtpd_sasl_auth_enable", value: "yes" }
    - { name: "smtpd_sasl_type", value: "dovecot" }
    - { name: "smtpd_sasl_path", value: "private/auth" }
    - { name: "smtpd_tls_auth_only", value: "yes" }
