---
- name: Add firewall rule for smtp
  ansible.posix.firewalld:
    zone: public
    service: smtp
    permanent: true
    state: enabled
    immediate: true
- name: Add firewall rule for smtp-submission
  ansible.posix.firewalld:
    zone: public
    service: smtp-submission
    permanent: true
    state: enabled
    immediate: true
