---
- name: Include certbot role
  include_role:
    name: certbot
- include: install.yaml
- include: config.yaml
- include: aliases.yaml
- include: service.yaml
- include: firewall.yaml
- include: pflogsumm.yaml
