---
- name: Include certbot role
  import_role:
    name: certbot
    allow_duplicates: no
- include: install.yaml
- include: config.yaml
- include: aliases.yaml
- include: service.yaml
- include: firewall.yaml
- include: pflogsumm.yaml

- include: simplelist.yaml
  when: postfix_simplelist_enable
