---
- name: Include certbot role
  ansible.builtin.import_role:
    name: nikdoof.certbot
    allow_duplicates: false
- ansible.builtin.include_tasks: install.yaml
- ansible.builtin.include_tasks: config.yaml
- ansible.builtin.include_tasks: aliases.yaml
- ansible.builtin.include_tasks: service.yaml
- ansible.builtin.include_tasks: firewall.yaml

- ansible.builtin.include_tasks: opendkim.yaml
  when: postfix_opendkim_enable
- ansible.builtin.include_tasks: pflogsumm.yaml
  when: postfix_pflogsumm_enable
- ansible.builtin.include_tasks: simplelist.yaml
  when: postfix_simplelist_enable
- ansible.builtin.include_tasks: procmail.yaml
