---
- name: Include certbot role
  import_role:
    name: certbot
    allow_duplicates: false
- include: install.yaml
- include: config.yaml
- include: aliases.yaml
- include: service.yaml
- include: firewall.yaml

- include: opendkim.yaml
  when: postfix_opendkim_enable
- include: pflogsumm.yaml
  when: postfix_pflogsumm_enable
- include: simplelist.yaml
  when: postfix_simplelist_enable
- include: procmail.yaml
