---
- name: Install pflogsumm
  ansible.builtin.package:
    name: "pflogsumm"
    state: present
- name: Install pflogsumm crontab
  copy:
    dest: /etc/cron.d/pflogsumm
    owner: root
    group: root
    mode: "0600"
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      @daily root pflogsumm -d yesterday --mailq /var/log/maillog*
