---
- name: Install procmail
  package:
    name: procmail
    state: installed
- name: Create basic procmail config
  file:
    dest: /etc/procmailrc
    mode: 0644
    owner: root
    group: root
    content: "MAILDIR=$HOME/Maildir/\nDEFAULT=$HOME/Maildir/\n"
