---
- name: Install procmail
  ansible.builtin.package:
    name: procmail
    state: installed
- name: Create basic procmail config
  ansible.builtin.copy:
    dest: /etc/procmailrc
    mode: 0644
    owner: root
    group: root
    content: "MAILDIR=$HOME/Maildir/\nDEFAULT=$HOME/Maildir/\n"
