---
- name: Install simplelist
  ansible.builtin.package:
    name: "simplelist"
    state: present

- name: Set SELinux context so Postfix can run Simplelist
  sefcontext:
    target: /usr/bin/simplelist.py
    setype: postfix_local_exec_t
    state: present

- name: Configure simplelist
  copy:
    dest: /etc/postfix/simplelist.yaml
    owner: root
    group: root
    mode: "0644"
    content: "{{ postfix_simplelist_config | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"

- name: Add alias to configured list
  lineinfile:
    dest: "/etc/aliases"
    regexp: "^{{ item }}:.*"
    line: '{{ item }}: "|/usr/bin/simplelist.py {{ item }}"'
    state: present
  loop: "{{ postfix_simplelist_config.lists.keys() | list }}"
  notify: new aliases
