---
- name: Install fcgiwrap
  package:
    name: fcgiwrap
    state: installed

- name: Enable fcgiwrap
  service:
    name: fcgiwrap@nginx.socket
    enabled: yes
    state: started

- name: Configure cgi in nginx
  copy:
    src: config/cgi.conf
    dest: /etc/nginx/default.d/cgi.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx

- name: Create cgi directory
  file:
    path: /var/www/cgi
    state: directory
    mode: "0755"
- name: Create requests directory
  file:
    path: /var/www/requests
    state: directory
    mode: "0700"

# Install python dependencies
- name: Install Python packages for CGI scripts
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - dnspython
      - markdown

# CGI scripts
- name: Deploy join.cgi
  copy:
    src: cgi/join.cgi
    dest: /var/www/cgi/join.cgi
    owner: root
    group: root
    mode: "0755"
- name: Deploy users.cgi
  copy:
    src: cgi/users.cgi
    dest: /var/www/cgi/users.cgi
    owner: root
    group: root
    mode: "0755"
- name: Deploy online.cgi
  copy:
    src: cgi/online.cgi
    dest: /var/www/cgi/online.cgi
    owner: root
    group: root
    mode: "0755"
- name: Deploy news.cgi
  copy:
    src: cgi/news.cgi
    dest: /var/www/cgi/news.cgi
    owner: root
    group: root
    mode: "0755"
- name: Deploy wiki.cgi
  copy:
    src: cgi/wiki.cgi
    dest: /var/www/cgi/wiki.cgi
    owner: root
    group: root
    mode: "0755"

