---
- name: Enable httpd_enable_cgi
  ansible.posix.seboolean:
    name: httpd_enable_cgi
    persistent: true
    state: true

- name: Install fcgiwrap
  ansible.builtin.package:
    name: fcgiwrap
    state: installed

- name: Enable fcgiwrap
  ansible.builtin.service:
    name: fcgiwrap@nginx.socket
    enabled: true
    state: started

# Install python dependencies
- name: Install Python packages for CGI scripts
  ansible.builtin.pip:
    name: "{{ packages }}"
  vars:
    packages:
      - dnspython
      - markdown
      - jinja2
      - python-frontmatter
      - utmp
