---
- name: Enable httpd_enable_cgi
  ansible.posix.seboolean:
    name: httpd_enable_cgi
    persistent: yes
    state: yes

- name: Install fcgiwrap
  package:
    name: fcgiwrap
    state: installed

- name: Enable fcgiwrap
  service:
    name: fcgiwrap@nginx.socket
    enabled: yes
    state: started

# Install python dependencies
- name: Install Python packages for CGI scripts
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - dnspython
      - markdown
      - jinja2
