---
- name: Install fcgiwrap
  package:
    name: fcgiwrap
    state: installed

- name: Enable fcgiwrap
  service:
    name: fcgiwrap@nginx.socket
    enabled: yes
    state: started

- name: Create cgi directory
  file:
    path: /var/www/cgi
    state: directory
    mode: "0755"
- name: Create requests directory
  file:
    path: /var/www/requests
    state: directory
    mode: "0700"

# Install python dependencies
- name: Install Python packages for CGI scripts
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - dnspython
      - markdown
