---
- name: Create cgi directory
  file:
    path: /var/www/cgi
    state: directory
    mode: '0755'
- name: Create requests directory
  file:
    path: /var/www/requests
    state: directory
    mode: '0700'

# CGI scripts
- name: Deploy join.cgi
  copy:
    src: ../files/cgi/join.cgi
    dest: /var/www/cgi/join.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy users.cgi
  copy:
    src: ../files/cgi/users.cgi
    dest: /var/www/cgi/users.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy online.cgi
  copy:
    src: ../files/cgi/online.cgi
    dest: /var/www/cgi/online.cgi
    owner: root
    group: root
    mode: '0755'
- name: Deploy news.cgi
  copy:
    src: ../files/cgi/news.cgi
    dest: /var/www/cgi/news.cgi
    owner: root
    group: root
    mode: '0755'