---
- name: Add firewall rule for http
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
- name: Add firewall rule for https
  firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled
