---
- name: Add firewall rule for http
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
    immediate: yes
- name: Add firewall rule for https
  ansible.posix.firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled
    immediate: yes
