---
- name: Add firewall rule for http
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
    immediate: true
- name: Add firewall rule for https
  ansible.posix.firewalld:
    zone: public
    service: https
    permanent: true
    state: enabled
    immediate: true
