---
- name: Install Packages
  dnf:
    name: "nginx"
    state: present
- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Configure userdirs in nginx
  copy:
    src: config/userdir.conf
    dest: /etc/nginx/default.d/userdir.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx

