---
- name: Install Packages
  dnf:
    name: "nginx"
    state: present
- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Install nginx.conf
  copy:
    src: config/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
- name: Copy redirect http config to nginx
  copy:
    src: "config/sites/http-redirect.conf"
    dest: "/etc/nginx/conf.d/http-redirect.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
- name: Create well-known folder for certbot
  file:
    path: /var/www/acme-challenge
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Restart nginx now, if needed
  meta: flush_handlers
