---
- name: Include certbot role
  include_role:
    name: certbot
- include: install.yaml
- include: firewall.yaml
- include: sites.yaml
- include: cgi.yaml
- include: website.yaml
- include: tildejsongen.yaml
