---
- name: Include certbot role
  import_role:
    name: certbot
    allow_duplicates: no
- include: install.yaml
- include: firewall.yaml
- include: sites.yaml
- include: cgi.yaml
- include: website.yaml
- include: tildejsongen.yaml
