---
- name: Copy SSL vhosts config to nginx
  copy:
    src: "config/sites/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
  with_items: "{{ www_sites }}"
- name: Build a list of all site files.
  set_fact:
    www_site_files: "{{ www_site_files|default(['http-redirect.conf', 'ip-redirect.conf']) }} + [ '{{ item }}.conf' ]"
  with_items: "{{ www_sites }}"
- name: Get a list of all files in /etc/nginx/conf.d/
  shell: ls -1 /etc/nginx/conf.d/
  register: contents
  changed_when: false
- debug:
    var: www_site_files
- debug:
    var: contents
- name: Remove unmanaged files
  file:
    path: "/etc/nginx/conf.d/{{ item }}"
    state: absent
  notify: restart nginx
  with_items: contents
  when: item not in www_site_files
