---
- name: Copy SSL vhosts config to nginx
  ansible.builtin.copy:
    src: "config/sites/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx
  loop: "{{ www_sites }}"
- name: Set default www_site_files fact.
  ansible.builtin.set_fact:
    www_site_files: ['http-redirect.conf', 'ip-redirect.conf']
- name: Build a list of all site files.
  ansible.builtin.set_fact:
    www_site_files: "{{ www_site_files | default(['http-redirect.conf', 'ip-redirect.conf']) }} + [ '{{ item }}.conf' ]"
  loop: "{{ www_sites }}"
- name: Get a list of all files in /etc/nginx/conf.d/
  ansible.builtin.command: /bin/ls -1 /etc/nginx/conf.d/
  register: www_nginx_confd_contents
  changed_when: false
- name: Remove unmanaged files
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ item }}"
    state: absent
  notify: Restart Nginx
  loop: "{{ www_nginx_confd_contents.stdout_lines }}"
  when: item not in www_site_files
