---
- name: Install tildejsongen
  dnf:
    name: tildejsongen
    state: installed
- name: Copy tildejsongen config
  copy:
    src: tildejsongen.ini
    dest: /etc/tildejsongen.ini
    owner: root
    group: root
    mode: "0600"
- name: Install tilejsongen crontab
  copy:
    dest: /etc/cron.d/tildejsongen
    owner: root
    group: root
    mode: "0600"
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      @hourly root tildejsongen
