---
- name: Install tildejsongen
  dnf:
    name: tildejsongen
    state: installed
- name: Copy tildejsongen config
  copy:
    src: tildejsongen.ini
    dest: /etc/tildejsongen.ini
    owner: root
    group: root
    mode: "0700"
- name: Setup crontab to update tilde.json
  copy:
    src: scripts/update-tildejson
    dest: /etc/cron.hourly/update-tildejson
    owner: root
    group: root
    mode: "0700"
