---
- name: Deploy website files
  git:
    repo: 'https://github.com/dimension-sh/www-site.git'
    dest: /var/www/dimension.sh/
    version: master
- name: Setup crontab to update the website
  copy:
    src: ../files/scripts/update-website
    dest: /etc/cron.hourly/update-website
    owner: root
    group: root
    mode: '0700'
- name: Create the drivel output file
  copy:
    content: ""
    dest: /var/www/dimension.sh/inc/drivel.html
    force: no
    owner: root
    group: users
    mode: '0664'



