---
- name: Install AIDE
  ansible.builtin.package:
    name: aide
    state: installed
  notify: init aide
- name: Install AIDE crontab
  ansible.builtin.copy:
    dest: /etc/cron.d/aide
    owner: root
    group: root
    mode: "0600"
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      0 5 * * * root /usr/sbin/aide --update; mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
