---
- name: Copy main CIS benchmark ruleset
  copy:
    src: auditd/cis-hardening.rules
    dest: /etc/audit/rules.d/cis-hardening.rules
    owner: root
    group: root
    mode: "0600"
- name: Copy privileged commands ruleset
  copy:
    src: auditd/privileged.rules
    dest: /etc/audit/rules.d/privileged.rules
    owner: root
    group: root
    mode: "0600"
