---
- name: Check if grub file exists
  stat:
    path: "{{ item }}"
  register: grub_results
  with_items:
    - /boot/grub2/grub.cfg
    - /boot/grub2/grubenv
  ignore_errors: True
- name: Change grub file modes
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0600"
  with_items: "{{ grub_results.results }}"
  when: item.stat.exists
- name: Change MOTD files security
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net
- name: Set cron file security
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop:
    - /etc/crontab
- name: Set cron.* directory security
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0700"
  loop:
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly
    - /etc/cron.d
