---
# Modify login.defs
- name: Set Default umask for Users
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "UMASK"
    line: "UMASK 077"
    state: present
- name: Set Home filemode
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "HOME_MODE"
    line: "HOME_MODE 0701"
    state: present
- name: Disable user groups
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "USERGROUPS_ENAB"
    line: "USERGROUPS_ENAB no"
    state: present
