---
- name: Install rsyslog
  ansible.builtin.package:
    name: rsyslog
    state: present
- name: Set FileCreateMode for rsyslog
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/00-filecreatemode.conf
    owner: root
    group: root
    mode: "0644"
    content: "$FileCreateMode 0640\n"
  notify: restart rsyslog
- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
