---
- name: Check if /var/gopher is checkout from git
  stat:
    path: /var/gopher/.git
  register: gopher_result_git
- name: Remove /var/gopher dir if not a git repo
  file:
    path: /var/gopher
    state: absent
  when: not gopher_result_git.stat.exists
- name: Deploy gophersite files
  git:
    repo: "https://github.com/dimension-sh/gopher-site.git"
    separate_git_dir: /usr/local/src/gopher-site
    dest: /var/gopher/
    version: master
