---
- name: Install Gophernicus
  ansible.builtin.package:
    name: gophernicus
    state: installed
- name: create override folder for gophernicus@.service
  ansible.builtin.file:
    path: /etc/systemd/system/gophernicus@.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Install systemd overrides
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/gophernicus@.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
