#!/bin/bash

USER=`whoami`
DATE=`date +"%Y-%m-%d %H:%M"`
MESSAGE=$(echo "$@"| sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')

if [ -z "$MESSAGE" ]; then
    echo "Usage: $0 <message>"
    exit 1
fi

echo "$DATE <b>${USER}</b>: ${MESSAGE}<br/>" >> /var/www/dimension.sh/inc/drivel.html
echo "Posted to Drivel"
exit 0