---
- name: Write borgmatic config
  template:
    src: config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: "0600"
- name: "Copy SSH key {{ item }} to borgmatic config folder"
  copy:
    src: "ssh_keys/{{ item }}"
    dest: "/etc/borgmatic/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ borgmatic_ssh_keys }}"
