---
- name: Install certbot
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - certbot
      - python3-certbot-dns-digitalocean
- name: Install nginx restart deploy-hook for certbot
  copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/nginx
    mode: "0755"
    owner: root
    group: root
    content: |
      #!/bin/sh
      /bin/systemctl restart nginx


