---
- name: Create /etc/molly
  ansible.builtin.file:
    path: /etc/molly
    state: directory
    mode: "0755"
- name: Copy molly.conf
  ansible.builtin.copy:
    src: "molly.conf"
    dest: "/etc/molly/molly.conf"
    owner: molly
    group: molly
    mode: "0644"
  notify: restart molly
- name: Start Molly Brown
  ansible.builtin.systemd:
    name: molly-brown.service
    enabled: true
    state: started
- name: Setup crontab to link users to the gemsite
  ansible.builtin.copy:
    src: scripts/link-gemini
    dest: /etc/cron.hourly/link-gemini
    owner: root
    group: root
    mode: "0700"

- name: Check if mkuser post.d exists
  ansible.builtin.stat:
    path: /etc/mkuser/post.d
  register: post_d_folder
- name: Setup link-gemini for mkuser post actions
  ansible.builtin.copy:
    src: scripts/link-gemini
    dest: /etc/mkuser/post.d/link-gemini
    owner: root
    group: root
    mode: "0700"
  when: post_d_folder.stat.exists and post_d_folder.stat.isdir
