---
- name: Create /etc/molly
  ansible.builtin.file:
    path: /etc/molly
    state: directory
    mode: "0755"
- name: Copy molly.conf
  ansible.builtin.copy:
    src: "molly.conf"
    dest: "/etc/molly/molly.conf"
    owner: molly
    group: molly
    mode: "0644"
  notify: restart molly
- name: Start Molly Brown
  ansible.builtin.systemd:
    name: molly-brown.service
    enabled: yes
    state: started
- name: Setup crontab to link users to the gemsite
  copy:
    src: scripts/link-gemini
    dest: /etc/cron.hourly/link-gemini
    owner: root
    group: root
    mode: "0700"
