---
- name: Include golang role
  ansible.builtin.import_role:
    name: gantsign.golang
    allow_duplicates: false
- name: Build molly-brown
  ansible.builtin.command: "{{ ansible_local.golang.general.home }}/bin/go get tildegit.org/solderpunk/molly-brown"
  args:
    creates: "/root/go/bin/molly-brown"
- name: Copy molly-brown executable
  ansible.builtin.copy:
    src: /root/go/bin/molly-brown
    dest: /usr/local/bin/molly-brown
    mode: "0755"
    setype: bin_t
    remote_src: true
- name: Create molly group
  ansible.builtin.group:
    name: molly
    system: true
- name: Create molly user
  ansible.builtin.user:
    name: molly
    group: molly
    home: /var/gemini
    create_home: false
    shell: /bin/false
    system: true
- name: Copy molly-brown.service
  ansible.builtin.copy:
    src: "molly-brown.service"
    dest: "/etc/systemd/system/molly-brown.service"
    owner: root
    group: root
    mode: "0644"
  notify: Reload Systemd
- name: Install molly-brown restart deploy-hook for certbot
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/molly-brown
    mode: "0755"
    owner: root
    group: root
    content: |
      #!/bin/sh
      /bin/systemctl Restart Molly-brown
- name: Refresh systemd now
  ansible.builtin.meta: flush_handlers
