---
- name: Include certbot role
  ansible.builtin.import_role:
    name: certbot
    allow_duplicates: false
- ansible.builtin.include_tasks: install.yaml
- ansible.builtin.include_tasks: config.yaml
- ansible.builtin.include_tasks: firewall.yaml
- ansible.builtin.include_tasks: site.yaml
