---
- name: Check if /var/gopher is checkout from git
  ansible.builtin.stat:
    path: /var/gemini/.git
  register: gemini_result_git
- name: Remove /var/gemini dir if not a git repo
  ansible.builtin.file:
    path: /var/gemini
    state: absent
  when: not gemini_result_git.stat.exists
- name: Deploy gemini site files
  ansible.builtin.git:
    repo: "https://github.com/dimension-sh/gemini-site.git"
    separate_git_dir: /usr/local/src/gemini-site
    dest: /var/gemini/
    version: main
