#!/bin/sh

source /etc/efingerd/log

if [ "$3" = "root" ]; then
    source /etc/efingerd/preamble
else
    user_folder="/home/${3}"

    # Plan
    printf "Plan:\\n"
    if [ -f "${user_folder}/.plan" ]; then
        sed 's/^/  /' "${user_folder}/.plan"
    else
        printf "No Plan.\n"
    fi

    # Pronouns
    if [ -f "${user_folder}/.pronouns" ]; then
        printf "Pronouns: "
        sed 's/^/  /' "${user_folder}/.pronouns"
    fi

    # Projects
    if [ -f "${user_folder}/.project" ]; then
        printf "Projects:\\n"
        sed 's/^/  /' "${user_folder}/.project"
    fi

    # Timezone
    if [ -f "${user_folder}/.tz" ]; then
        printf "Timezone: "
        cat "${user_folder}/.tz"
        printf "\n"
    fi

    # Online status
    if finger "$3" | grep -q 'On since'; then
        printf "Online.\n"
    fi

fi

exit 0
