#!/bin/bash

cat /etc/motd.d/00-logo | sed 's/\x1b\[[0-9;]*m//g'

echo "dimension.sh is a shared linux shell system (or pubnix), open to everyone and anyone to"
echo "use, learn, and experiment."
echo ""
echo "If you're interested in joining check out the website: https://dimension.sh"
