---
- name: Install ansible pre-reqs
  ansible.builtin.package:
    name: sudo
    state: present
- name: Ensure that includedir in sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
- name: Create ansible group
  ansible.builtin.group:
    name: ansible
    system: true
- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    system: true
    group: ansible
    shell: /bin/bash
    home: /var/lib/ansible
    comment: Ansible User
- name: Install SSH keys into ansible user
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ item }}"
  loop: "{{ ansible_keys }}"
- name: Add user "ansible" to sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: true
    validate: "visudo -cf %s"
- name: Remove all SSH keys from root
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: absent
