---
- name: Install fail2ban
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fail2ban
      - fail2ban-selinux
- name: Set ignoreip
  community.general.ini_file:
    path: /etc/fail2ban/jail.local
    section: DEFAULT
    option: ignoreip
    value: "{{ fail2ban_ignoreip | join(' ') }}"
    mode: "0644"
    backup: yes
  notify: restart fail2ban
- name: Set default ban time
  community.general.ini_file:
    path: /etc/fail2ban/jail.local
    section: DEFAULT
    option: bantime
    value: "600"
    mode: "0644"
    backup: yes
  notify: restart fail2ban
- name: Enable sshd jail
  community.general.ini_file:
    path: /etc/fail2ban/jail.local
    section: sshd
    option: enabled
    value: "true"
    mode: "0644"
  notify: restart fail2ban
- name: Start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
