---
- name: Install Packages
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Add firewall rule for ssh
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes
