---
- name: Install Packages
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Add firewall rule for ssh
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: true
    state: enabled

- name: Start Firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
