---
- name: Create /etc/motd.d
  file:
    path: /etc/motd.d
    state: directory
    mode: "0755"
- name: Add MOTD Logo
  copy:
    src: motd/00-logo
    dest: /etc/motd.d/00-logo
    owner: root
    group: root
    mode: "0644"
