---
- name: Install and configure node_exporter
  tags:
    - node_exporter
  block:
    - name: Install node_exporter
      ansible.builtin.package:
        name: golang-github-prometheus-node-exporter
        state: installed

    - name: Start node_exporter
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: true

    - name: Add firewall rule for node_exporter
      ansible.posix.firewalld:
        zone: public
        rich_rule: rule family="{% if item is ansible.utils.ipv6 %}ipv6{% else %}ipv4{% endif %}" source address="{{ item }}" port protocol="tcp" port="9100" accept
        permanent: true
        state: enabled
        immediate: true
      loop: "{{ node_exporter_source_ips }}"
      loop_control:
        label: "{{ item }}"
