---
- name: Install Common Packages
  dnf:
    name: "{{ common_packages }}"
    state: present
- name: Install Group Packages
  dnf:
    name: "{{ common_packages }}"
    state: present
- name: Remove unneeded Packages
  dnf:
    name: "{{ remove_packages }}"
    state: absent
