---
- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
- name: Install Group Packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
- name: Remove unneeded Packages
  ansible.builtin.package:
    name: "{{ remove_packages }}"
    state: absent

- name: Install Digital Ocean Agent
  ansible.builtin.package:
    name: do-agent
    state: installed
  when: ansible_system_vendor == 'DigitalOcean'

- name: Install VMware Tools
  ansible.builtin.package:
    name: open-vm-tools
    state: installed
  when: ansible_system_vendor == 'VMware, Inc.'
