---
- name: Install yum-utils
  dnf:
    name: yum-utils
    state: present

- name: Install Dimension RPMs repo
  command: yum-config-manager --add-repo http://dimension-sh.github.io/dimension-rpms/dimension-rpms.repo
  args:
    creates: /etc/yum.repos.d/dimension-rpms.repo

# CentOS
- name: Check if Powertools Repo exists
  stat:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
  register: centospowertools_repo_file
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable PowerTools repo
  lineinfile:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    regexp: "^enabled="
    line: "enabled=1"
  when: ansible_facts['os_family'] == "RedHat" and centospowertools_repo_file.stat.exists

# Rocky
- name: Check if Powertools Repo exists
  stat:
    path: /etc/yum.repos.d/Rocky-PowerTools.repo
  register: rockypowertools_repo_file
  when: ansible_facts['os_family'] == "Rocky"

- name: Enable PowerTools repo
  lineinfile:
    path: /etc/yum.repos.d/Rocky-PowerTools.repo
    regexp: "^enabled="
    line: "enabled=1"
  when: ansible_facts['os_family'] == "Rocky" and rockypowertools_repo_file.stat.exists

- name: Install epel-release Packages
  dnf:
    name: epel-release
    state: present
