---
- name: Install yum-utils
  dnf:
    name: yum-utils
    state: present
- name: Install Dimension RPMs repo
  command: yum-config-manager --add-repo http://dimension-sh.github.io/dimension-rpms/dimension-rpms.repo
  args:
    creates: /etc/yum.repos.d/dimension-rpms.repo

- name: Check if Powertools Repo exists
  stat:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
  register: powertools_repo_file
- name: Enable PowerTools repo
  lineinfile:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    regexp: "^enabled="
    line: "enabled=1"
  when: powertools_repo_file.stat.exists

- name: Install epel-release Packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - epel-release
