---
- name: Install yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Install Dimension RPMs repo
  ansible.builtin.command: yum-config-manager --add-repo http://dimension-sh.github.io/dimension-rpms/dimension-rpms.repo
  args:
    creates: /etc/yum.repos.d/dimension-rpms.repo

- name: Set Powertools repo name for RedHat
  ansible.builtin.set_fact:
    common_powertools_repofile: CentOS-Linux-PowerTools.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Set Powertools repo name for Rocky
  ansible.builtin.set_fact:
    common_powertools_repofile: Rocky-PowerTools.repo
  when: ansible_facts['os_family'] == "Rocky"

- name: Check if PowerTools Repo exists
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/{{ common_powertools_repofile }}"
  register: common_powertools_repofile_stat

- name: Enable PowerTools repo
  ansible.builtin.lineinfile:
    path: "/etc/yum.repos.d/{{ common_powertools_repofile }}"
    regexp: "^enabled="
    line: "enabled=1"
  when: common_powertools_repofile_stat.stat.exists

- name: Install epel-release Packages
  ansible.builtin.package:
    name: epel-release
    state: present
