---
- name: Install yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Install Dimension RPMs repo
  ansible.builtin.command: yum-config-manager --add-repo http://dimension-sh.github.io/dimension-rpms/dimension-rpms.repo
  args:
    creates: /etc/yum.repos.d/dimension-rpms.repo

- name: Set Powertools repo name for RedHat
  ansible.builtin.set_fact:
    powertools_repofile: CentOS-PowerTools.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Set Powertools repo name for Rocky
  ansible.builtin.set_fact:
    powertools_repofile: Rocky-PowerTools.repo
  when: ansible_facts['os_family'] == "Rocky"

- name: Check if PowerTools Repo exists
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/{{ powertools_repofile }}"
  register: powertools_repo_file

- name: Enable PowerTools repo
  ansible.builtin.lineinfile:
    path: "/etc/yum.repos.d/{{ powertools_repofile }}"
    regexp: "^enabled="
    line: "enabled=1"
  when: powertools_repo_file.stat.exists

- name: Install epel-release Packages
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Add DO Agent repository
  ansible.builtin.yum_repository:
    file: digitalocean-agent
    name: sonar
    description: do agent
    baseurl: https://repos.insights.digitalocean.com/yum/do-agent/$basearch
    gpgcheck: true
    gpgkey: https://repos.insights.digitalocean.com/sonar-agent.asc
    enabled: true
    state: present
  when: ansible_system_vendor == 'DigitalOcean'
