---
postfix_mynetworks:
  - "127.0.0.0/8"
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"
postfix_virtual_domains: []
postfix_virtual_aliases: []
postfix_smtpd_helo_restrictions:
  - permit_mynetworks
  - reject_non_fqdn_helo_hostname
  - reject_invalid_helo_hostname
  - permit
postfix_smtpd_sender_restrictions:
  - permit_mynetworks
  - reject_non_fqdn_sender
  - reject_unknown_sender_domain
  - permit
postfix_smtpd_recipient_restrictions:
  - reject_invalid_hostname
  - reject_unknown_recipient_domain
  - reject_unauth_pipelining
  - permit_mynetworks
  - reject_non_fqdn_recipient
  - reject_unauth_destination
  - reject_rbl_client dnsbl.dronebl.org
  - reject_rbl_client zen.spamhaus.org
  - reject_rbl_client bl.spamcop.net
  - reject_rbl_client dnsbl.sorbs.net
  - reject_rbl_client cbl.abuseat.org
  - reject_rbl_client b.barracudacentral.org
  - reject_rbl_client dnsbl-1.uceprotect.net
  - permit
