---
- name: Common roles to all hostgroups
  hosts: all
  become: true
  roles:
    - role: common
    - role: nikdoof.cis
    - role: nikdoof.certbot
      tags:
        - certbot
    - role: nikdoof.borgmatic

- name: Shell hostgroup roles
  hosts: shell
  become: true
  roles:
    - role: shell
      tags:
        - shell
    - role: efingerd
    - role: news
    - role: www
      tags:
        - www
    - role: gopher
      tags:
        - www
        - gopher
    - role: gemini
      tags:
        - www
        - gemini

- name: Mail hostgroup roles
  hosts: mail
  become: true
  roles:
    - role: postfix
      tags:
        - mail
    - role: dovecot
      tags:
        - mail
