name: Deploy Production
"on":
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            main.yaml
          args: "-p --parseable-severity"
  deploy-production:
    name: Deploy - Production
    environment: production
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Call Dimension Tower to Deploy
        uses: informaticsmatters/trigger-awx-action@v1
        with:
          template: ${{ secrets.DIMENSION_TOWER_TEMPLATEID }}
          template-host: ${{ secrets.DIMENSION_TOWER_URL }}
          template-user: ${{ secrets.DIMENSION_TOWER_USER }}
          template-user-password: ${{ secrets.DIMENSION_TOWER_PASSWORD }}
