name: Deploy Production
"on":
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            main.yaml
          args: "-p --parseable-severity"
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Call Dimension Tower to Deploy
        uses: informaticsmatters/trigger-awx-action@v1
        with:
          template: ${{ secrets.DIMENSION_TOWER_TEMPLATEID }}
          template-host: ${{ secrets.DIMENSION_TOWER_URL }}
          template-user: ${{ secrets.DIMENSION_TOWER_USER }}
          template-user-password: ${{ secrets.DIMENSION_TOWER_PASSWORD }}

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
